kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: mongo-pvc
  namespace: afghan-dep

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv
  storageClassName: standard