kind: Secret
apiVersion: v1

metadata:
  name: secret
  namespace: afghan-dep

type: Opaque

stringData:
  mongo-name: "admin"
  mongo-pass: "admin123"
  mongodb-uri: "mongodb://admin:admin123@mongodb-svc:27017/afghan?authSource=admin"
  jwt-secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0."
  email-host: "smtp.gmail.com"
  email-user: "rajeelsiddiqui3@gmail.com"
  email-pass: "abll wvge dhho fumf"
  email-from: "noreply@boostgg.com"
  redis-url: "https://tidy-hen-120769.upstash.io"
  redis-token: "gQAAAAAAAdfBAAIgcDJiMGVlMWI0OWVlODY0ZjZjOWE2YmNhZmYxMmU3ODRmNQ"
