kind: PersistentVolume
apiVersion: v1

metadata:
  name: upload-pv
  namespace: afghan-dep

spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: "/data/upload/pv"
