kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1

metadata:
  name: mongodb-vpa
  namespace: ammax

spec:
  targetRef:
    kind: StatefulSet
    apiVersion: apps/v1
    name: mongo-deployment

  updatePolicy:
    updateMode: "Off"

  resourcePolicy:
    containerPolicies:
      - containerName: mongo-container
        controlledResources: ["cpu", "memory"]
